baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Iceberg LaFortuna"
   headline = "A silly dog on the internet"
   image = "author.jpg"  # path relative to static directory

  links = [
     { bluesky = "https://bsky.app/profile/icebergfortuna.bsky.social" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
